# Generated by Django 5.0.6 on 2024-06-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='images',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images/product_images'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images_set', to='product_management.products'),
        ),
    ]
