# Generated by Django 5.0.6 on 2024-07-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_products_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='images',
            field=models.ImageField(default='', upload_to='images/product_images'),
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=100)),
                ('variant_stock', models.PositiveIntegerField(default=0)),
                ('variant_status', models.BooleanField(default=True)),
                ('colour_code', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.products')),
            ],
        ),
    ]
