# Generated by Django 5.0.6 on 2024-07-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
