# Generated by Django 5.0.6 on 2024-07-08 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_product_variant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
