# Generated by Django 5.0.6 on 2024-07-17 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0007_product_variant_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(default='Order Placed', max_length=100)),
                ('payment_option', models.CharField(default='cash_on_delivery', max_length=100)),
                ('order_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=400)),
                ('street_name', models.CharField(max_length=300)),
                ('pin_number', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product_variant')),
            ],
        ),
    ]
